name: eclipse-viewshed
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal
  - rasterio
  - geopandas
  - pyogrio
  - pyproj
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - ipykernel
  - requests
  - beautifulsoup4
  - pytest
  - openssl<3.5.7
  - pip
  - pip:
      - pvlib
